#!/bin/bash

# Define authors
author1="Faith Akinyi <faithomondi1331@gmail.com>"
author2="Emma Ogutu <atisemma26@gmail.com>"

# Output header
echo "# File @generated by generate_authors.sh. DO NOT EDIT."
echo "# This file lists all contributors to the repository."
echo "# See generate-authors.sh to make modifications."
echo

# Output authors
echo "$author1"
echo "$author2"
